### Crear cliente 1
POST http://localhost:8080/api/customers
Content-Type: application/json

{
  "id": 1,
  "firstName": "Juan",
  "lastName": "Perez",
  "email": "juan.perez@example.com",
  "gender": "M",
  "phoneNumber": "1123456789",
  "address": {
    "addressLine": "Av. 9 de Julio 1234",
    "city": "Buenos Aires",
    "region": "CABA",
    "postalCode": "C1001",
    "country": "Argentina"
  }
}

### Actualizar datos cliente 1
PUT http://localhost:8080/api/customers/1
Content-Type: application/json

{
  "gender": "M"
}

### Crear el cliente 2
POST http://localhost:8080/api/customers
Content-Type: application/json

{
  "id": 2,
  "firstName": "Maria",
  "lastName": "Gomez",
  "gender": "F",
  "email": "maria.gomez@example.com",
  "phoneNumber": "1134567890",
  "address": {
    "addressLine": "Calle Falsa 5678",
    "city": "Rosario",
    "region": "Santa Fe",
    "postalCode": "2000",
    "country": "Argentina"
  }
}

### Crear cliente 9
POST http://localhost:8080/api/customers
Content-Type: application/json

{
  "id": 9,
  "gender": "M",
  "lastName": "Palmera",
  "firstName": "Flavio",
  "email": "flavio.palmera@olaverde.com.ar",
  "phoneNumber": "1155555555",
  "address": {
    "addressLine": "Avenida Libertador 4321",
    "city": "Buenos Aires",
    "region": "CABA",
    "postalCode": "1426",
    "country": "Argentina"
  }
}

### Obtener el cliente 1
GET http://localhost:8080/api/customers/1

### Obtener todos los clientes
GET http://localhost:8080/api/customers

### Obtener clientes femeninos
GET http://localhost:8080/api/customers/filter
Content-Type: application/json

{
  "gender": "F"
}


### Eliminar cliente 1
DELETE http://localhost:8080/api/customers/1

### Eliminar cliente 2
DELETE http://localhost:8080/api/customers/2
